name: Deploy

# Trigger after build.yml completes successfully
on:
  workflow_run:
    workflows: ["Docker Build"]
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    name: Deploy to plainrandom.com
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted
    steps:
      - name: Deploy
        run: |
          echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u USERNAME --password-stdin
          docker compose -f /opt/stacks/plainrandom/compose.yaml pull
          docker compose -f /opt/stacks/plainrandom/compose.yaml up --force-recreate --build -d
          docker image prune -f
          docker logout